"""Synthetic UVC backend used by the unit suite.

This backend satisfies the :class:`LibUvcBackend` Protocol with in-memory
data so the driver and the plugin control loop can be exercised without a
PureThermal dongle on the bus. It lives in the test tree on purpose: it
synthesises temperatures, so it must never be reachable from the plugin's
production import path, where a fabricated reading would be published as
live telemetry.
"""

from __future__ import annotations

from typing import Iterator

from altnautica_thermal_camera.uvc_backend import (
    DEFAULT_HEIGHT,
    DEFAULT_WIDTH,
    UvcDeviceInfo,
    UvcFrame,
)

__all__ = ["MockUvcBackend"]


class MockUvcBackend:
    """In-memory backend that produces synthetic radiometric frames.

    A ``width`` x ``height`` grid is generated by :meth:`_synthesise`.
    Background pixels sit at the configured ambient temperature; a hot
    disc centred in the frame climbs to the configured peak, so a
    downstream spot meter has a known value to read at the centre
    reticle and known extrema across the frame.

    Constructor knobs:

    * ``width``, ``height`` set the frame size.
    * ``peak_celsius`` sets the temperature at the centre of the hot
      disc.
    * ``ambient_celsius`` sets the cool-background temperature.
    * ``device_count`` configures how many synthetic devices
      ``enumerate`` returns; ``0`` models an empty bus.
    """

    def __init__(
        self,
        *,
        width: int = DEFAULT_WIDTH,
        height: int = DEFAULT_HEIGHT,
        ambient_celsius: float = 22.0,
        peak_celsius: float = 60.0,
        device_count: int = 1,
        firmware_version: str = "1.2.3",
    ) -> None:
        self._width = width
        self._height = height
        self._ambient = ambient_celsius
        self._peak = peak_celsius
        self._device_count = device_count
        self._firmware = firmware_version
        self._opened: set[str] = set()
        self._sequence = 0
        self._radiometry_enabled: dict[str, bool] = {}
        self._ffc_calls: dict[str, int] = {}
        self._tlinear_resolution: dict[str, float] = {}

    @property
    def opened_devices(self) -> set[str]:
        """Serial numbers of devices currently open. Test helper."""

        return set(self._opened)

    @property
    def ffc_calls(self) -> dict[str, int]:
        """Per-device FFC trigger counts. Test helper."""

        return dict(self._ffc_calls)

    def enumerate(self) -> list[UvcDeviceInfo]:
        return [
            UvcDeviceInfo(
                serial=f"PT2-MOCK-{i:03d}",
                vid=0x1E4E,
                pid=0x0100,
                bus_path=f"/mock/usb/{i}",
                firmware_version=self._firmware,
                width=self._width,
                height=self._height,
            )
            for i in range(self._device_count)
        ]

    def open(self, device: UvcDeviceInfo) -> None:
        self._opened.add(device.serial)

    def close(self, device: UvcDeviceInfo) -> None:
        self._opened.discard(device.serial)

    def frames(self, device: UvcDeviceInfo) -> Iterator[UvcFrame]:
        if device.serial not in self._opened:
            raise RuntimeError(
                f"frames requested on closed device: {device.serial}"
            )
        while device.serial in self._opened:
            yield self._synthesise(device)

    def set_radiometry(self, device: UvcDeviceInfo, enabled: bool) -> None:
        self._radiometry_enabled[device.serial] = enabled

    def set_tlinear_resolution(
        self, device: UvcDeviceInfo, k_per_count: float
    ) -> None:
        if k_per_count not in (0.01, 0.1):
            raise ValueError(
                "Lepton 3.5 TLinear resolution must be 0.01 or 0.1 K per count"
            )
        self._tlinear_resolution[device.serial] = k_per_count

    @property
    def tlinear_resolutions(self) -> dict[str, float]:
        """Per-device locked resolution. Test helper."""

        return dict(self._tlinear_resolution)

    def trigger_ffc(self, device: UvcDeviceInfo) -> None:
        self._ffc_calls[device.serial] = self._ffc_calls.get(device.serial, 0) + 1

    def firmware_version(self, device: UvcDeviceInfo) -> str:
        return self._firmware

    def _synthesise(self, device: UvcDeviceInfo) -> UvcFrame:
        from altnautica_thermal_camera.tlinear import y16_from_celsius

        self._sequence += 1
        ambient_y16 = y16_from_celsius(self._ambient)
        peak_y16 = y16_from_celsius(self._peak)
        cx = self._width // 2
        cy = self._height // 2
        radius = max(4, min(self._width, self._height) // 8)
        radius_sq = radius * radius

        pixels: list[int] = []
        for y in range(self._height):
            dy = y - cy
            for x in range(self._width):
                dx = x - cx
                dist_sq = dx * dx + dy * dy
                if dist_sq <= radius_sq:
                    blend = 1.0 - (dist_sq / radius_sq)
                    raw = int(round(ambient_y16 + blend * (peak_y16 - ambient_y16)))
                else:
                    raw = ambient_y16
                pixels.append(raw)

        timestamp_ns = self._sequence * 115_000_000  # ~8.7 Hz
        return UvcFrame(
            timestamp_ns=timestamp_ns,
            sequence=self._sequence,
            width=self._width,
            height=self._height,
            y16=tuple(pixels),
            metadata={"device_serial": device.serial},
        )
