"""UVC backend abstraction for the thermal camera driver.

The PureThermal 2 dongle exposes the FLIR Lepton 3.5 as a USB UVC
video device. Production agent installs reach the dongle through a
native libuvc binding. The native binding is intentionally NOT wired
in this version: the spec calls for landing the abstraction first
and the real binding when hardware procurement closes.

This module ships:

* :class:`LibUvcBackend` Protocol describing the surface the driver
  needs from any UVC backend.

* :class:`UvcDeviceInfo` and :class:`UvcFrame` data classes that the
  Protocol's methods exchange.

* :class:`MockUvcBackend` test fixture that produces deterministic
  synthetic Y16 frames (a cool background with a hot spot in the
  middle). Unit tests build their pipelines on top of this so the
  driver can be exercised end-to-end without a real device.

When the libuvc binding lands it will live in a sibling module that
also satisfies :class:`LibUvcBackend`, with no other code change in
the driver or the plugin entry point.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterator, Protocol, runtime_checkable

DEFAULT_WIDTH = 160
DEFAULT_HEIGHT = 120
DEFAULT_FPS = 8.7


@dataclass(frozen=True)
class UvcDeviceInfo:
    """Summary of a UVC device discovered on the bus.

    The driver builds a :class:`ados.sdk.drivers.camera.CameraCandidate`
    from this and lets the peripheral manager arbitrate.
    """

    serial: str
    vid: int
    pid: int
    bus_path: str
    firmware_version: str
    width: int = DEFAULT_WIDTH
    height: int = DEFAULT_HEIGHT
    fps: float = DEFAULT_FPS
    radiometric: bool = True
    itar_restricted: bool = False


@dataclass(frozen=True)
class UvcFrame:
    """One Y16 frame yielded by the backend.

    ``y16`` is a flat ``tuple[int, ...]`` of length ``width * height`` so
    consumers can iterate without forcing a numpy dependency. The
    driver wraps this into the SDK's ``FrameBuffer`` shape.
    """

    timestamp_ns: int
    sequence: int
    width: int
    height: int
    y16: tuple[int, ...]
    metadata: dict[str, object] = field(default_factory=dict)


@runtime_checkable
class LibUvcBackend(Protocol):
    """The slice of libuvc the driver depends on.

    A concrete backend must implement ``enumerate``, ``open``,
    ``close``, ``frames``, ``set_radiometry``, ``trigger_ffc``, and
    ``firmware_version``. Implementations may be synchronous; the
    driver wraps them in ``asyncio.to_thread`` calls when the host
    runs the iterator from an async loop.
    """

    def enumerate(self) -> list[UvcDeviceInfo]: ...

    def open(self, device: UvcDeviceInfo) -> None: ...

    def close(self, device: UvcDeviceInfo) -> None: ...

    def frames(self, device: UvcDeviceInfo) -> Iterator[UvcFrame]: ...

    def set_radiometry(self, device: UvcDeviceInfo, enabled: bool) -> None: ...

    def trigger_ffc(self, device: UvcDeviceInfo) -> None: ...

    def firmware_version(self, device: UvcDeviceInfo) -> str: ...


class MockUvcBackend:
    """In-memory backend that produces synthetic radiometric frames.

    A 160x120 grid is generated by :meth:`_synthesise`. Background
    pixels sit at roughly 22 deg C; a hot disc in the middle climbs to
    a configurable peak (default 60 deg C). The disc shifts a few
    pixels frame-to-frame so a downstream spot meter can verify that
    its reading tracks the source.

    Constructor knobs:

    * ``width``, ``height`` set the frame size.
    * ``peak_celsius`` sets the temperature at the centre of the hot
      disc in steady state.
    * ``ambient_celsius`` sets the cool-background temperature.
    * ``device_count`` configures how many synthetic devices
      ``enumerate`` returns.
    """

    def __init__(
        self,
        *,
        width: int = DEFAULT_WIDTH,
        height: int = DEFAULT_HEIGHT,
        ambient_celsius: float = 22.0,
        peak_celsius: float = 60.0,
        device_count: int = 1,
        firmware_version: str = "1.2.3",
    ) -> None:
        self._width = width
        self._height = height
        self._ambient = ambient_celsius
        self._peak = peak_celsius
        self._device_count = device_count
        self._firmware = firmware_version
        self._opened: set[str] = set()
        self._sequence = 0
        self._radiometry_enabled: dict[str, bool] = {}
        self._ffc_calls: dict[str, int] = {}

    @property
    def opened_devices(self) -> set[str]:
        """Serial numbers of devices currently open. Test helper."""

        return set(self._opened)

    @property
    def ffc_calls(self) -> dict[str, int]:
        """Per-device FFC trigger counts. Test helper."""

        return dict(self._ffc_calls)

    def enumerate(self) -> list[UvcDeviceInfo]:
        return [
            UvcDeviceInfo(
                serial=f"PT2-MOCK-{i:03d}",
                vid=0x1E4E,
                pid=0x0100,
                bus_path=f"/mock/usb/{i}",
                firmware_version=self._firmware,
                width=self._width,
                height=self._height,
            )
            for i in range(self._device_count)
        ]

    def open(self, device: UvcDeviceInfo) -> None:
        self._opened.add(device.serial)

    def close(self, device: UvcDeviceInfo) -> None:
        self._opened.discard(device.serial)

    def frames(self, device: UvcDeviceInfo) -> Iterator[UvcFrame]:
        if device.serial not in self._opened:
            raise RuntimeError(
                f"frames requested on closed device: {device.serial}"
            )
        while device.serial in self._opened:
            yield self._synthesise(device)

    def set_radiometry(self, device: UvcDeviceInfo, enabled: bool) -> None:
        self._radiometry_enabled[device.serial] = enabled

    def trigger_ffc(self, device: UvcDeviceInfo) -> None:
        self._ffc_calls[device.serial] = self._ffc_calls.get(device.serial, 0) + 1

    def firmware_version(self, device: UvcDeviceInfo) -> str:
        return self._firmware

    def _synthesise(self, device: UvcDeviceInfo) -> UvcFrame:
        from altnautica_thermal_camera.tlinear import y16_from_celsius

        self._sequence += 1
        ambient_y16 = y16_from_celsius(self._ambient)
        peak_y16 = y16_from_celsius(self._peak)
        cx = self._width // 2
        cy = self._height // 2
        radius = max(4, min(self._width, self._height) // 8)
        radius_sq = radius * radius

        pixels: list[int] = []
        for y in range(self._height):
            dy = y - cy
            for x in range(self._width):
                dx = x - cx
                dist_sq = dx * dx + dy * dy
                if dist_sq <= radius_sq:
                    blend = 1.0 - (dist_sq / radius_sq)
                    raw = int(round(ambient_y16 + blend * (peak_y16 - ambient_y16)))
                else:
                    raw = ambient_y16
                pixels.append(raw)

        timestamp_ns = self._sequence * 115_000_000  # ~8.7 Hz
        return UvcFrame(
            timestamp_ns=timestamp_ns,
            sequence=self._sequence,
            width=self._width,
            height=self._height,
            y16=tuple(pixels),
            metadata={"device_serial": device.serial},
        )
