"""Plugin-side MAVLink encoders + emit helpers.

Three messages cover the optical-flow + range injection surface:

* OPTICAL_FLOW (#100)        — flow-sensor scalar output.
* OPTICAL_FLOW_RAD (#106)    — angular-rate flow (PX4FLOW class).
* DISTANCE_SENSOR (#132)     — downward rangefinder injection.

Wire format and CRC_EXTRA fingerprints match the agent framework's
canonical encoders at ``ados.services.mavlink.encoders.{vision,rangefinder}``;
the values below are the dialect-generated bytes for the MAVLink common
message set, identical to what pymavlink computes from the field-type +
field-name digest.

Each ``emit_*`` helper:
    1. Reads ``time_sync.clock_align.ClockAlign`` to convert the plugin's
       ``time.monotonic_ns()`` into FC clock space (microseconds).
    2. Packs a complete MAVLink v2 frame (sys + comp + seq + CRC).
    3. Dispatches via ``ctx.mavlink.send(bytes, component_id=...)``.

Plugin code calls ``emit_*`` rather than building bytes by hand. The
host MAVLink router accepts the framed bytes verbatim and forwards them
to every connected link.
"""

from __future__ import annotations

import asyncio
import itertools
import logging
import struct
import time
from typing import Final, Sequence

from ._framing import pack_v2

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Message ids + CRC_EXTRA fingerprints
# ---------------------------------------------------------------------------

MSG_ID_OPTICAL_FLOW: Final[int] = 100
MSG_ID_OPTICAL_FLOW_RAD: Final[int] = 106
MSG_ID_DISTANCE_SENSOR: Final[int] = 132

CRC_OPTICAL_FLOW: Final[int] = 175
CRC_OPTICAL_FLOW_RAD: Final[int] = 138
CRC_DISTANCE_SENSOR: Final[int] = 85


# ---------------------------------------------------------------------------
# Pre-built struct packers (wire order, little-endian).
# ---------------------------------------------------------------------------

_PACK_OPTICAL_FLOW: Final[struct.Struct] = struct.Struct("<QfffhhBBff")
_PACK_OPTICAL_FLOW_RAD: Final[struct.Struct] = struct.Struct("<QIfffffIfhBB")
_PACK_DISTANCE_SENSOR: Final[struct.Struct] = struct.Struct("<IHHHBBBBff4fB")


# Default sys_id used by the plugin when it sends as comp 198 (peripheral
# alongside the autopilot). Matches the host's source_system convention
# of treating every onboard component as belonging to sys 1 unless the
# flight stack declares otherwise.
DEFAULT_SYS_ID: Final[int] = 1


class _SeqCounter:
    """Per-component monotonic SEQ counter, wraps at 256.

    MAVLink defines SEQ per (sys, comp) pair. A single plugin owns one
    component (comp 198) so a single counter is sufficient. The counter
    is process-local; on a runner restart it resets, which is fine
    because routers tolerate SEQ resets on link reattach.
    """

    def __init__(self) -> None:
        self._it = itertools.count()

    def next(self) -> int:
        return next(self._it) & 0xFF


_seq = _SeqCounter()


# ---------------------------------------------------------------------------
# Frame builders
# ---------------------------------------------------------------------------


def build_optical_flow(
    *,
    sys_id: int,
    comp_id: int,
    seq: int,
    time_usec: int,
    sensor_id: int,
    flow_x: int,
    flow_y: int,
    flow_comp_m_x: float,
    flow_comp_m_y: float,
    quality: int,
    ground_distance: float,
    flow_rate_x: float = 0.0,
    flow_rate_y: float = 0.0,
) -> bytes:
    """Pack an OPTICAL_FLOW (#100) v2 frame."""
    payload = _PACK_OPTICAL_FLOW.pack(
        time_usec,
        float(flow_comp_m_x),
        float(flow_comp_m_y),
        float(ground_distance),
        int(flow_x),
        int(flow_y),
        int(sensor_id) & 0xFF,
        int(quality) & 0xFF,
        float(flow_rate_x),
        float(flow_rate_y),
    )
    return pack_v2(
        msg_id=MSG_ID_OPTICAL_FLOW,
        crc_extra=CRC_OPTICAL_FLOW,
        payload=payload,
        sys_id=sys_id,
        comp_id=comp_id,
        seq=seq,
    )


def build_optical_flow_rad(
    *,
    sys_id: int,
    comp_id: int,
    seq: int,
    time_usec: int,
    sensor_id: int,
    integration_time_us: int,
    integrated_x: float,
    integrated_y: float,
    integrated_xgyro: float,
    integrated_ygyro: float,
    integrated_zgyro: float,
    temperature: int,
    quality: int,
    time_delta_distance_us: int,
    distance: float,
) -> bytes:
    """Pack an OPTICAL_FLOW_RAD (#106) v2 frame (PX4FLOW-style)."""
    payload = _PACK_OPTICAL_FLOW_RAD.pack(
        int(time_usec),
        int(integration_time_us),
        float(integrated_x),
        float(integrated_y),
        float(integrated_xgyro),
        float(integrated_ygyro),
        float(integrated_zgyro),
        int(time_delta_distance_us),
        float(distance),
        int(temperature),
        int(sensor_id) & 0xFF,
        int(quality) & 0xFF,
    )
    return pack_v2(
        msg_id=MSG_ID_OPTICAL_FLOW_RAD,
        crc_extra=CRC_OPTICAL_FLOW_RAD,
        payload=payload,
        sys_id=sys_id,
        comp_id=comp_id,
        seq=seq,
    )


def build_distance_sensor(
    *,
    sys_id: int,
    comp_id: int,
    seq: int,
    time_boot_ms: int,
    min_distance_cm: int,
    max_distance_cm: int,
    current_distance_cm: int,
    sensor_type: int,
    sensor_id: int,
    orientation: int,
    covariance: int,
    horizontal_fov: float = 0.0,
    vertical_fov: float = 0.0,
    quaternion: Sequence[float] = (0.0, 0.0, 0.0, 0.0),
    signal_quality: int = 0,
) -> bytes:
    """Pack a DISTANCE_SENSOR (#132) v2 frame."""
    if len(quaternion) != 4:
        raise ValueError(
            f"quaternion must have length 4, got {len(quaternion)}"
        )
    payload = _PACK_DISTANCE_SENSOR.pack(
        int(time_boot_ms) & 0xFFFFFFFF,
        int(min_distance_cm) & 0xFFFF,
        int(max_distance_cm) & 0xFFFF,
        int(current_distance_cm) & 0xFFFF,
        int(sensor_type) & 0xFF,
        int(sensor_id) & 0xFF,
        int(orientation) & 0xFF,
        int(covariance) & 0xFF,
        float(horizontal_fov),
        float(vertical_fov),
        float(quaternion[0]),
        float(quaternion[1]),
        float(quaternion[2]),
        float(quaternion[3]),
        int(signal_quality) & 0xFF,
    )
    return pack_v2(
        msg_id=MSG_ID_DISTANCE_SENSOR,
        crc_extra=CRC_DISTANCE_SENSOR,
        payload=payload,
        sys_id=sys_id,
        comp_id=comp_id,
        seq=seq,
    )


# ---------------------------------------------------------------------------
# Emit helpers (the plugin-public surface)
# ---------------------------------------------------------------------------


def _fc_time_usec(clock_align: "ClockAlign | None") -> int:
    """Resolve the FC-clock timestamp in microseconds for an emit call."""
    mono_ns = time.monotonic_ns()
    if clock_align is None:
        return mono_ns // 1000
    return clock_align.convert_to_fc_clock(mono_ns) // 1000


async def emit_optical_flow(
    ctx: "object",
    *,
    component_id: int,
    sensor_id: int,
    flow_x: int,
    flow_y: int,
    flow_comp_m_x: float,
    flow_comp_m_y: float,
    quality: int,
    ground_distance: float,
    clock_align: "ClockAlign | None" = None,
    flow_rate_x: float = 0.0,
    flow_rate_y: float = 0.0,
    sys_id: int = DEFAULT_SYS_ID,
) -> None:
    """Send one OPTICAL_FLOW message on the plugin's MAVLink component."""
    frame = build_optical_flow(
        sys_id=sys_id,
        comp_id=component_id,
        seq=_seq.next(),
        time_usec=_fc_time_usec(clock_align),
        sensor_id=sensor_id,
        flow_x=flow_x,
        flow_y=flow_y,
        flow_comp_m_x=flow_comp_m_x,
        flow_comp_m_y=flow_comp_m_y,
        quality=quality,
        ground_distance=ground_distance,
        flow_rate_x=flow_rate_x,
        flow_rate_y=flow_rate_y,
    )
    await _send(ctx, frame, component_id)


async def emit_optical_flow_rad(
    ctx: "object",
    *,
    component_id: int,
    sensor_id: int,
    integration_time_us: int,
    integrated_x: float,
    integrated_y: float,
    integrated_xgyro: float,
    integrated_ygyro: float,
    integrated_zgyro: float,
    temperature: int,
    quality: int,
    time_delta_distance_us: int,
    distance: float,
    clock_align: "ClockAlign | None" = None,
    sys_id: int = DEFAULT_SYS_ID,
) -> None:
    """Send one OPTICAL_FLOW_RAD message on the plugin's MAVLink component."""
    frame = build_optical_flow_rad(
        sys_id=sys_id,
        comp_id=component_id,
        seq=_seq.next(),
        time_usec=_fc_time_usec(clock_align),
        sensor_id=sensor_id,
        integration_time_us=integration_time_us,
        integrated_x=integrated_x,
        integrated_y=integrated_y,
        integrated_xgyro=integrated_xgyro,
        integrated_ygyro=integrated_ygyro,
        integrated_zgyro=integrated_zgyro,
        temperature=temperature,
        quality=quality,
        time_delta_distance_us=time_delta_distance_us,
        distance=distance,
    )
    await _send(ctx, frame, component_id)


async def emit_distance_sensor(
    ctx: "object",
    *,
    component_id: int,
    min_distance_cm: int,
    max_distance_cm: int,
    current_distance_cm: int,
    sensor_type: int,
    sensor_id: int,
    orientation: int,
    covariance: int,
    horizontal_fov: float = 0.0,
    vertical_fov: float = 0.0,
    quaternion: Sequence[float] = (0.0, 0.0, 0.0, 0.0),
    signal_quality: int = 0,
    clock_align: "ClockAlign | None" = None,
    time_boot_ms: int | None = None,
    sys_id: int = DEFAULT_SYS_ID,
) -> None:
    """Send one DISTANCE_SENSOR message on the plugin's MAVLink component.

    ``time_boot_ms`` may be supplied directly; otherwise it is derived
    from the time-sync offset converted to milliseconds. DISTANCE_SENSOR
    uses a millisecond uint32, not the microsecond uint64 of OPTICAL_FLOW.
    """
    if time_boot_ms is None:
        time_boot_ms = _fc_time_usec(clock_align) // 1000
    frame = build_distance_sensor(
        sys_id=sys_id,
        comp_id=component_id,
        seq=_seq.next(),
        time_boot_ms=time_boot_ms,
        min_distance_cm=min_distance_cm,
        max_distance_cm=max_distance_cm,
        current_distance_cm=current_distance_cm,
        sensor_type=sensor_type,
        sensor_id=sensor_id,
        orientation=orientation,
        covariance=covariance,
        horizontal_fov=horizontal_fov,
        vertical_fov=vertical_fov,
        quaternion=quaternion,
        signal_quality=signal_quality,
    )
    await _send(ctx, frame, component_id)


async def _send(ctx: "object", frame: bytes, component_id: int) -> None:
    """Dispatch a framed message on the plugin context's MAVLink facade.

    Tolerates either a real :class:`PluginContext` (async ``ctx.mavlink.send``)
    or a test double that records calls synchronously.
    """
    mavlink = getattr(ctx, "mavlink", None)
    if mavlink is None:
        log.warning("emit dropped: ctx.mavlink missing")
        return
    send = getattr(mavlink, "send", None)
    if send is None:
        log.warning("emit dropped: ctx.mavlink.send missing")
        return
    try:
        result = send(frame, component_id=component_id)
        if asyncio.iscoroutine(result):
            await result
    except Exception as exc:  # noqa: BLE001
        log.warning("emit failed: %s", exc)


# Forward import for type checkers only; avoids a circular import at runtime.
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from altnautica_vision_nav.time_sync.clock_align import ClockAlign  # noqa: F401
